name: Premier workflow
on: workflow_dispatch
jobs:
  premier-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Dit bonjour
        run: echo "Hello world !"
      - name: autre step
        run: echo "Goodbye"
